services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MARIADB_DATABASE=biblioteca
    #volumes:
    #  - ${PWD}/mariadb:/var/lib/mysql

  dbadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1