services:
  db:
    container_name: db
    image: 'mysql:latest'
    restart: always
    hostname: db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=biblioteca
    #volumes:
    #  - /var/lib/mysql

  dbadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1

  biblioteca:
    build: ./
    image: biblioteca
    container_name: biblioteca
    ports:
      - 8081:8081
    depends_on:
      - db
